/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9a777daed054bed99b475e49b975604b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
